/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    int sum1, sum2, sum3, sum4;
    System.out.println(new App().getGreeting());
    sum1 = new Calculate().sum(2, 3);
    sum2 = new Calculate().sumTo(1, 10);
    sum3 = new Calculate().sumOddTo(1, 10);
    sum4 = new Calculate().sumEvenTo(1, 10);
    System.out.println("Sum of 2 and 3 is" + sum1);

  }
}
